### ISSUE TITLE
System.ArgumentException: No definition for type 'ExampleEvent', have you remembered to load it during EventFlow initialization

### ISSUE THREAD

**Issue by GreatGodJackChen** [rasmus/EventFlow#1018]
builder.Services
    .AddEventFlow(o => o.AddEvents(new List<Type> {  typeof(ExampleEvent) })
    .AddCommands(new List<Type> { typeof(ExampleCommand) })
    .AddCommandHandlers(new List<Type> { typeof(ExampleCommandHandler) })
    .UseInMemoryReadStoreFor<ExampleReadMode>()
    //.UseMongoDbEventStore()
    //.UseMongoDbSnapshotStore()
    //.ConfigureMongoDb(mongoDbConnectionString, databaseName)
    //.AddSnapshots(typeof(ControlGroupSnapshot))
    );
exception：
System.ArgumentException: No definition for type 'ExampleEvent', have you remembered to load it during EventFlow initialization
   at EventFlow.Core.VersionedTypes.VersionedTypeDefinitionService`3.GetDefinition(Type type)

**Comment by iron-dom** [comment]
Hi

I'm using EventFLow 0.83.4713 

AddEventFlow (options =>
        {
            
            options.AddDefaults(typeof(EventImpl).Assembly)
                .RegisterServices(sr =>
                {
                    sr.Register<IReadModelDescriptionProvider, ReadModelDescriptionProvider>(Lifetime.Singleton, true);
                    sr.Register<IMongoDbEventSequenceStore, MongoDbEventSequenceStore>(Lifetime.Singleton);
                })
                .AddEvents( new Type[] { typeof(CreatedEvent) })
                .UseMongoDbEventStore()
                .UseMongoDbSnapshotStore()
                .UseConsoleLog()
                ;
        });


And have the same Issue with "CreatedEvent" ..
