### ISSUE TITLE
Update EventFlow.MongoDB to 2.28

### ISSUE THREAD

**Issue by Jaben** [rasmus/EventFlow#1038]
First, thank you for this excellent library -- it's genuinely one of the best. You guys do a great job -- I know how thankless open source can be -- so THANK YOU.

But the latest MongoDB.Driver breaks bindings. I can't compile my solution with EventFlow anymore:

![image](https://github.com/user-attachments/assets/b372a15d-7fcd-4ca4-9768-253babdb56a7)

I'll do a PR here today/tomorrow for this update.

**Comment by rasmus** [comment]
Thanks for reporting and creating the PR ❤️

**Comment by rasmus** [comment]
Released in 0.84.4
