### ISSUE TITLE
Getting 1.0 over the finish line

### ISSUE THREAD

**Issue by Jaben** [rasmus/EventFlow#1041]
@rasmus I know getting a big release over the finish line is tough -- I'm struggling with the same thing with Papercut -- but is there anything I can do to help? What, in your mind, needs to happen to be ready for release? Builds? More testing?

Thanks for this wonderful project!

**Comment by rasmus** [comment]
It's mostly the documentation and the upgrade guide, really wanted to get those done before. I was thinking of merely cutting a release and getting the last few modules converted along the way when that is done. The main reason for the delay is some major restructure at work, basically the company is spitting in two and layoffs are planned. It has taken up a considerably amount of energy, leaving little to EventFlow the last few months. With that, and a family with wife and two kids, my open-source contribution takes bottom priority. But any support would be awesome


(EDIT: make it more readable)

**Comment by rasmus** [comment]
@Jaben there's light at the end of the tunnel for the company split and I'm getting some time to actually move some of the documentation (with the help from GitHub Workspaces). Still a lot to go through, but will hopefully get it in a ready state.

**Comment by rasmus** [comment]
https://geteventflow.net/ is now properly up and running with the old docs.geteventflow.net configured with a permanent redirect. There's a high chance that I have forgotten something in the conversion, but at least its in a better state now. More importantly, its easier to do smaller changes now that the site is in place.

**Comment by rasmus** [comment]
I'll close this issue as its more of a discussion. I have provided a link to the (old) EventFlow discord server on https://geteventflow.net/ (at the bottom). Anyone wanting to discuss the future of EventFlow is welcome to join the server! It really helps motivating me to do EventFlow when there's people on the "other end".

https://discord.gg/QfgNPs5WxR
