### ISSUE TITLE
Support various IoC providers

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#126]
Complex projects are invariably tied to their IoC provider at multiple levels making the adoption of EventFlow problematic if support is not available for a chosen IoC. `IResolver` provides solid foundation to an IoC abstraction enabling the implementation of IoC providers.

http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison
https://github.com/danielpalme/IocPerformance

**Comment by rasmus** [comment]
Small note, to set an other IoC, one merely needs to call the `UseServiceRegistration(...)` right after creating the `EventFlowOptions`. The `EventFlowOptionsAutofacExtensions` illistrates how it could be done.

**Comment by JC008** [comment]
Time for a silly question: Is EventFlow dependent on Autofac in any way? I have been going through the code and the sym links in ` EventFlow.Configuration.Registrations` are confusing me on this issue.

**Comment by rasmus** [comment]
@JC008 The "core" NuGet package isn't, but it does a IL merge with Autofac embedding it into the assembly. All the Autofac assembly types are marked as internal and not accessible outside the assembly. The EventFlow.Autofac package has reference to some of the same files, but this assembly isn't marked as internal allowing you to access and cast the types.
In short words, I was lazy and didn't want to write a IoC for the core package but wanted a good IoC for  it and used Autofac.
You can see this if you use e.g. dotPeek and disassemble the core package.

**Comment by JC008** [comment]
@rasmus So the support for any IoC is there already in `UseServiceRegistration(...)` and the Autofac element is internal only. That is very cool to say the least, thanks for the detailed feedback.

**Comment by rasmus** [comment]
@JC008 No worries. I wrote a tiny bit about it in the docs as well. Hard to find though `/Documentation/Customize.md` (at the bottom)
