### ISSUE TITLE
Test projects being modified by VS2015

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#129]
I am having the same issue described [here](https://connect.microsoft.com/VisualStudio/feedback/details/800245/vs2013rc-adds-to-vs2012-c-project-section-itemgroup) for `EventFlow.MsSql.Tests.csproj`, `EventFlow.Owin.Tests.csproj`, `EventFlow.RabbitMq.Tests.csproj` when opening the `EventFlow` solution.

**Comment by rasmus** [comment]
I'm not sure I understand the problem correctly. Every time you open the EventFlow solution, it adds the following section?

```xml
<ItemGroup>
  <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
</ItemGroup>
```

And that is basically marking it as a test project? If that's the case, and its harmless, I'll just update the projects and removing the inconvenience?

**Comment by JC008** [comment]
Sorry - let me clarify

1. __My__ VS2015 adds the service guid - why does __your__ VS[version] not add it? Perhaps you are using VS2012.
2. If I did a pull request without knowing what was causing it - the pull request should not be accepted.

I will it to all the test projects as it is VS2015 and seems legitimate - VS2015 is speeding up the project loading time - see the third comment by _Oleg [MSFT]_. It's not an inconvenience as such but a _what is that and why does it keep happening_ question that is now answered.

**Comment by rasmus** [comment]
@JC008 I'm using VS2015 myself and haven't seen the additions, which was why I was very confused.

**Comment by JC008** [comment]
@rasmus I found the cause - if you use the NUnit Test Runner in VS it adds the service group. If you use Resharper to run tests - it does not. Mystery solved.

**Comment by rasmus** [comment]
@JC008 Great, thanks for looking into it
