### ISSUE TITLE
Aggregate/event caching

### ISSUE THREAD

**Issue by rasmus** [rasmus/EventFlow#15]
Make it possible to do custom aggregate/event caching and provide an in-memory implementation that can be used

**Comment by tabro** [comment]
@rasmus It should be extendable in order to support third party cache implementations (i.e. memcached)

**Comment by rasmus** [comment]
@tabro Sure. The framework should provide a default in-memory implementation that does it a fairly good job and then allow other to override it using the existing registration scheme.

**Comment by rasmus** [comment]
@tabro The in-memory should use the `MemoryCache` and then be registered as a singleton.

https://msdn.microsoft.com/en-us/library/system.runtime.caching.memorycache%28v=vs.110%29.aspx
