### ISSUE TITLE
Provide security foundation in EventFlow for Commands and Queries

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#159]
Commands and queries are the primary interaction points for EventFlow implementation consumers and could be the preferred location to apply an authorization check before allowing a command to be queued or a query to be handled.

**Comment by rasmus** [comment]
@JC008 If you have such needs you should implement them using a decorator of the service. Have a look at the documentation. Providing a generic security feature would clutter the framework and I would like not to have it if possible.

https://github.com/rasmus/EventFlow/blob/develop/Documentation/Customize.md#decorating-implementations

Would implementing a decorator with the security checks solve your need?

**Comment by JC008** [comment]
@rasmus Using a decorator does solve the issue. I think the word *foundation* in my comment is too strong and should not be taken to mean an implementation - guidance and examples would suffice and address a question many developers will raise.

Thanks.

**Comment by rasmus** [comment]
@JC008 Good point about the guidance. EventFlow documentation is still in a poor state. I have updated the FAQ for now with the question as its a valid concern and one I have considered myself for our own platform.

https://github.com/rasmus/EventFlow/blob/develop/Documentation/FAQ.md#how-can-i-ensure-that-only-specific-users-can-execute-commands
