### ISSUE TITLE
git lfs and icon-256.png

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#197]
@rasmus No matter what I try - `icon-256.png` is marked as modified after checking out into a clean `EventFlow` clone. If I commit the change and checkout any new branch - `icon-256.png` is back marked as modified. I'm using SourceTree and also updated its embedded git . 

`git lfs ls-files` show that `icon-256.png` is not tracked as a `lfs` file.

Any ideas or suggestions?

I found some links on SO but nothing helps.
[Git lfs (Large File Storage) says lfs managed files are modified after a git lfs pull](http://stackoverflow.com/questions/34685689/git-lfs-large-file-storage-says-lfs-managed-files-are-modified-after-a-git-lfs
)
[Git LFS always shows image files as changed?](http://stackoverflow.com/questions/34395587/git-lfs-always-shows-image-files-as-changed)

`git lfs env`:
```
$ git lfs env
git-lfs/1.1.0 (GitHub; windows 386; go 1.5.1; git 258acf1)
git version 2.6.1.windows.1

Endpoint=https://github.com/JC008/EventFlow.git/info/lfs (auth=basic)
Endpoint (rasmus)=https://github.com/rasmus/EventFlow.git/info/lfs (auth=none)
LocalWorkingDir=C:\Users\Jaco\Sources\EventFlow
LocalGitDir=C:\Users\Jaco\Sources\EventFlow\.git
LocalGitStorageDir=C:\Users\Jaco\Sources\EventFlow\.git
LocalMediaDir=C:\Users\Jaco\Sources\EventFlow\.git\lfs\objects
TempDir=C:\Users\Jaco\Sources\EventFlow\.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
git config filter.lfs.smudge = "git-lfs smudge %f"
git config filter.lfs.clean = "git-lfs clean %f"
```

`git lfs status`:
```
On branch develop
Git LFS objects to be pushed to origin/develop:


Git LFS objects to be committed:


Git LFS objects not staged for commit:

```

`git lfs ls-files`
```
f3c6f40cd4 * .paket/paket.bootstrapper.exe
78ae28505e * icon-128.png
```

**Comment by rasmus** [comment]
@JC008 `icon-256.png` is not tracked by LFS as its from before LFS was out. I haven't seen the problem on my other workstations but it would make sense to move it to LFS.

**Comment by JC008** [comment]
@rasmus now it makes sense - one of the links I found indicated a similar cause - items added before LFS and the `.gitattributes` now catches it via the wildcard:

```
*.png filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
```

**Comment by JC008** [comment]
@rasmus Can you add the icon to lfs - it's a showstopper for me.

**Comment by rasmus** [comment]
@JC008 Yes, I'll do it now... I can understand that's very annoying.

**Comment by rasmus** [comment]
@JC008 Its fixed in the ´develop´ and ´sqlite´ branches.
