### ISSUE TITLE
Custom Hangfire Job Title?

### ISSUE THREAD

**Issue by ylbillyli** [rasmus/EventFlow#205]
I have been using the IJob and IJobScheduler to queue jobs on Hangfire, but couldn't get the Job Name displayed right on the hangfire dashboard even with the [DisplayName] attribute or overriding the ToString() method on the Job. Is this supported by EventFlow?

![image](https://cloud.githubusercontent.com/assets/13381578/13244758/b9e99a58-da43-11e5-8b7c-3e530282f757.png)

**Comment by rasmus** [comment]
@ylbillyli You are right, that would be supported by EventFlow and I'll look into it.

**Comment by rasmus** [comment]
@ylbillyli The #206 is now live in release v0.27.1765

**Comment by ylbillyli** [comment]
Thx @rasmus I believe #206 will close this off
