### ISSUE TITLE
Hangfire JobScheduler and Autofac Activator

### ISSUE THREAD

**Issue by oliveiracdz** [rasmus/EventFlow#218]
I'm using Autofac as IoC container of EventFlow.
When i've tried to configure HangFire as JobScheduler, I ran into this issue.
I need the container to register the Activator for HangFire recurring jobs. But the extension method `UseAutofacContainerBuilder` needs to have HangFire already configured.
Maybe i'm missing something on the order of things, can you help me? 

```
        public void Configuration(IAppBuilder app)
        {
            var builder = new ContainerBuilder();

            // Container registrations...

            var container = EventFlowOptions.New
                .UseAutofacContainerBuilder(builder)
                .UseHangfireJobScheduler() // This line throws, cause I did not initialized the HangFire yet.
                .ConfigEventStore()
                // More configs...
                .CreateContainer();

            // I need the container here to configure HangFire activator for recurring jobs.
            // so I can not register HangFire before.
            GlobalConfiguration.Configuration.UseAutofacActivator(container); 

            app.UseHangfireServer();
            app.UseAutofacMiddleware(container);
        }
```

The exception:
> An exception was thrown while executing a resolve operation. See the InnerException for details. ---> JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API. (See inner exception for details.), An exception was thrown while executing a resolve operation. See the InnerException for details. ---> JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API. (See inner exception for details.), An exception was thrown while executing a resolve operation. See the InnerException for details. ---> JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API. (See inner exception for details.), An exception was thrown while executing a resolve operation. See the InnerException for details. ---> JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API. (See inner exception for details.)

**Comment by rasmus** [comment]
@oliveiracdz Have a look at the Hangfire integration tests to get an idea. There are multiple ways of setting up Hangfire and I didn't want EventFlow to dictate any of it.

https://github.com/rasmus/EventFlow/blob/develop/Source/EventFlow.Hangfire.Tests/Integration/HangfireJobSchedulerTests.cs

**Comment by oliveiracdz** [comment]
Hi @rasmus!

It worked! The trick was to use [DelegatingActivator](https://github.com/rasmus/EventFlow/blob/develop/Source/EventFlow.Hangfire.Tests/Integration/HangfireJobSchedulerTests.cs#L82) instead [Hangfire.Autofac package](https://github.com/HangfireIO/Hangfire.Autofac).

Thank you! :+1:
