### ISSUE TITLE
Questions: Exception Handling for CommandBus and EventDispatcher

### ISSUE THREAD

**Issue by ylbillyli** [rasmus/EventFlow#229]
@rasmus  Thanks for the work and previous reply. They are very useful. Forgive me if there is an answer to thiese already. We have come up with these two questions. Hope you could give us some advice on them.

##### CommandBus
I might mis-understand on this but I notice that the `_transientFaultHandler` seems no longer getting used in `CommandBus`. So would EventFlow still retry on optimistic concurrency ex?

##### DispatchToEventSubscribers
In the private `DispatchToSubscriberAsync` method, it logs and swallow any subscribers' exceptions. What is the reason for swallowing the exception or should this be configurable? When subscribers has unhandled ex sneaking out, there is something wrong and I would prefer to have it bubble up and stop further execution. And since this is a private method, we can't really just decorate the class and customise this bit to rethorw. We use a tmp fix for our project by decorate the `ILog.Error` to rethrow the ex to avoid having to copy the whole class and customize. What would be your recommended approach on dealing with subscribers' exceptions?

**Comment by rasmus** [comment]
@ylbillyli Please continue to give feedback on EventFlow, especially if you are suspicious of a design flaw or bug.

**CommandBus**
That functionality has been move to the new `AggregateStore.UpdateAsync` method which the `CommandBus` uses.

**DispatchToEventSubscribers**
The idea was that any error originating from subscribers should have been handled within the subscriber and not bubble all the way back to the publisher of a command. Handling of all possible unhandled exceptions from subscribers, which includes `DomainErrors` from commands publishes as a result of events published from the first command, would be almost impossible in most cases.

```
-> CommandA
 -> Event1
  -> Subscriber
    -> CommandB
      -> DomainError thrown from aggregate
 -> Event2
```

In the above case I would like to have the `DomainError` (or other exception) handled within the `Subscriber` as the publisher of the `CommandA` will have a hard time figuring out what to do. The handling within the subscriber could e.g. be to publish a correcting command.

An alternative way of looking at it, would be that this simulates the events being handled asynchronously by another process. In many of our systems we publish the events to RabbitMQ and handle them in other processes, applications or even servers.

But, you do have a fair point as swallowing exceptions is generally a bad idea and it should be possible to configure it when done. So, I think I`ll create a PR that makes sure that the `DispatchToEventSubscribers` gathers up all the exceptions that all subscribes throw and throw an `AggregateException` containing them all as inner exceptions. I'll then make it configurable to have the `DomainEventPublisher` to swallow the exceptions or not.

What do you think?

**Comment by ylbillyli** [comment]
@rasmus Sorry for delayed reply. I think that would be perfect as we are using eventflow on the same server and we are already trying to handle all known possible exceptions from our subscribers, however, for unknown/unexpected exceptions that we aren't handling, that usually means a bug in our system, we would like them to bubble up such that we can hard stop and display an system error message to the web interface. For these kind of unexpected exception, I think it would be neater to handle them by the top level global exception handler in our WebAPI project instead of having to put try catch in every subscribers?

**Comment by rasmus** [comment]
@ylbillyli You point is certainly valid and I have create a PR illustrating the changes that could allow the exceptions to be handled at the top level in PR #230. Will that work for you? I still need to clean it up and write several tests for it.

**Comment by ylbillyli** [comment]
@rasmus that looks perfect to me. I will close this issue then. Thanks
