### ISSUE TITLE
SnapshotAggregateRoot does not throw DuplicateOperationException

### ISSUE THREAD

**Issue by ppilev** [rasmus/EventFlow#799]
Hello,

Could you please help me with the following scenario:
I have a distinct command executed against snapshot aggregate root but once a snapshot is created I cannot see DuplicateOperationException thrown anymore for the same command.

Looking at the code I've found that once a snapshot version is created the aggregate cannot track the previous source ids anymore and so I can publish the same distinct commands I already did.

Could you please confirm that's expected and is it then a responsibility for my aggregate ensuring the DuplicateOperationException gets thrown based on its snapshot state.

**Comment by rasmus** [comment]
This sounds like a bug

**Comment by WardenUnleashed** [comment]
This behavior occurs because the `SourceId` of events are stored within the aggregate, when replayed from the EventStore. When loaded from a snapshot, the SourceId of all events already applied to the snapshot are not being stored.

I submitted a MR that appends the source ids to the snapshot metadata and reapplies those source ids to the Aggregate when reloaded from the snapshot which should fix this behavior.

**Comment by ppilev** [comment]
I've just checked the proposed fix and if I got it correctly each source id gets written and stored into the snapshot. I'm concerned in regard such solution because of the snapshot size growth after processing a few hundred (in my case thousand) commands, unless I'm missing something.

What I'm doing currently is to enforce the idempotency check at the persistence level - in my case separate table with a composite PK by SourceId and AggregateId columns.

**Comment by WardenUnleashed** [comment]
The number of previous source Ids stored in an aggregate is set by the aggregate itself, with a default size of [10]. (https://github.com/eventflow/EventFlow/blob/develop-v1/Source/EventFlow/Aggregates/AggregateRoot.cs#L43)

Therefore the amount stored on the snapshot will be equivalent to the size set in the aggregate.

**Comment by rasmus** [comment]
Fixed in #808

**Comment by rasmus** [comment]
Vil be fixed with 0.82
