### ISSUE TITLE
EventStore ReadAllEventsForwardAsync is populating all of the data from all services

### ISSUE THREAD

**Issue by DureSameen** [rasmus/EventFlow#802]
We have a single eventstore connected to all microservices. Now we are creating a data retrieval logic, to populate a microservice data in the startup. But the following line populating all data even from other services too. so it is causing exception in serialization    

`allEventsSlice = await _connection.ReadAllEventsForwardAsync(nextPosition, pageSize, false) ;`

How can we populate a single type only  i-e  only from following types.

`var typeList = _dataRetrievalConfiguration.ReadModelAssembly.DefinedTypes.Where(type =>   type.Name != "LookUpEnumReadModel" &&  !type.IsInterface && !type.IsAbstract && type.ImplementedInterfaces.Any(inter=>  inter == typeof(IReadModel))).ToList();
            typeList.ForEach(async x =>
            {
                await _populator.PopulateAsync(x, cancellationToken);
            });`

**Comment by rasmus** [comment]
Hi @DureSameen I'm not very familiar with EventStore, but would you be able to create a small exploratory test that illustrate your problem?

If there is a but, we'll need a fix for it.

**Comment by DureSameen** [comment]
I have created two microservices

https://github.com/DureSameen/EventFlowWithElasticSearch/tree/DataRetreveial
https://github.com/maree16/EventFlowForOrganization


The first one include logic of data retrieval.

1. Create environment variables. as described in readme.
2.  Add some data using both api 
3.  Turn on data retrieval  switch in write api ,
4.   All data from eventstore will read to the data retrieval routine.

**Comment by DureSameen** [comment]
any progress on this issue?

**Comment by rasmus** [comment]
Hi @DureSameen none. The EventStore part of EventFlow is mainly maintained by others. Would you be up for doing a pull request for it?
