### ISSUE TITLE
ReadModel with explicitly implemented interface is not updated

### ISSUE THREAD

**Issue by ibebbs** [rasmus/EventFlow#803]
Hi,

Just getting started with EventFlow but found an issue that tripped me up.

If an `IReadModel` explicitly implements the `IAmReadModelFor<Aggregate, Identity, Event>` interface, the Apply method is for this interface is not called.

For example:

```c#
public class PersonIdentifier : IReadModel, IAmReadModelFor<Aggregate, Identity, Event>
{
    void IAmReadModelFor<Aggregate, Identity, Event>.Apply(IReadModelContext context, IDomainEvent<Aggregate, Identity, Event> domainEvent)
    {
        // this will never be called
       throw new NotImplementedException();
    }
}
```

I believe it may be related to how the method is dynamically invoked from here: https://github.com/eventflow/EventFlow/blob/3c09676a867956158c34f2afff06683f4950df9e/Source/EventFlow/ReadStores/ReadModelDomainEventApplier.cs#L66

Thanks for the awesome project!

**Comment by rasmus** [comment]
This seems like a bug, thanks for reporting it.

Is it correctly invoked if you implement it as this?

```csharp
public void Apply(
  IReadModelContext context, IDomainEvent<Aggregate, Identity, Event> domainEvent)
  {
    throw new NotImplementedException();
  }
```

**Comment by ibebbs** [comment]
Hi Rasmus, thanks for getting back to me.

Yes, the apply method is called correctly after changing it from an explicitly implemented interface method to a normal public method.

Once I'm a little more familiar with EventFlow I'll be happy to prepare a PR but I imagine you'd be able to correct this much quicker.

**Comment by rasmus** [comment]
@ibebbs thanks for verifying, I'll see if I can get it fixed.

**Comment by rasmus** [comment]
Hi @ibebbs I spent a few minutes trying out a PR, but couldn't get the reflection right. Will try again soon
