### ISSUE TITLE
Publish External Event on Read Model Update

### ISSUE THREAD

**Issue by ibebbs** [rasmus/EventFlow#805]
Hi,

Managed to get a relatively complex EventFlow system (hosted in ASP.NET core webservice, events written to EventStore and ReadModels to MongoDB) really quickly (~1 day) and am super impressed EventFlow!

I'd now like to drive downstream systems from changes to read models. While I can monitor MongoDb directly for changes, I was wondering if there is a way within EventFlow to publish an external event (i.e. a different EventStore stream, RabbitMQ, etc) when a read model gets updated?

Thanks

**Comment by rasmus** [comment]
Thanks and pretty impressive doing it in one day! If its open source, I'd like to add a link to the readme to help others with better examples to get started,

There isn't anything built-in for publishing events on read models to other services. But a general API in the EventFlow core would be useful as an extension point.

**Comment by ibebbs** [comment]
Only possible to get it done so quickly due to how well this project implements the underlying CQRS/ES patterns. That said, I did need to collate best-practices from a number of different places so understand why you're keen to provide better examples.

Unfortunately the current project is not open source but I do maintain a [blog](https://ian.bebbs.co.uk) so, time-permitting, will try to cover setting up a solution like this as a post with associated repo. While I'm at it, I may even be able to set up a few "dotnet new" templates as it's something I was really hoping to find when first looking at EventFlow.

Regarding extension points for after a read model has been updated, I took a look at `ReadStoreManager.UpdateReadStoresAsync` and it seems like it would be a pretty simple change to add something after the call to `await ReadModelStore.UpdateAsync`... but what?

I don't know EventFlow very well yet but my gut feel is that it should be something akin to the `ISubscribeSynchronousTo`. Something like this maybe:

```c#
public interface ISubscribeSynchronousTo<TAggregate, in TIdentity, in TReadModel> : ISubscribe
    where TAggregate : IAggregateRoot<TIdentity>
    where TIdentity : IIdentity
    where TReadModel: IReadModel
{
    Task HandleAsync(
        IReadModelEvent<TAggregate, TIdentity, TReadModel> readModelEvent
        CancellationToken cancellationToken);
}
```

Then a `ReadModelEventPublisher` (similar to `DomainEventPublisher`) could be implemented and injected into `ReadModelManager`.

What do you think?

**Comment by ibebbs** [comment]
Just coming back to this and I've realised that this facility isn't really needed given read stores are updated _prior_ to domain events being published to subscribers, as shown in `DomainEventPublisher` below:

```c#
public async Task PublishAsync(
    IReadOnlyCollection<IDomainEvent> domainEvents,
    CancellationToken cancellationToken)
{
    cancellationToken = _cancellationConfiguration.Limit(cancellationToken, CancellationBoundary.BeforeUpdatingReadStores);
    await PublishToReadStoresAsync(domainEvents, cancellationToken).ConfigureAwait(false);

    cancellationToken = _cancellationConfiguration.Limit(cancellationToken, CancellationBoundary.BeforeNotifyingSubscribers);
    await PublishToSubscribersOfAllEventsAsync(domainEvents, cancellationToken).ConfigureAwait(false);
    ...
}
```

Therefore I can subscribe to pertinent domain events and publish external (i.e. integration) events knowing that should downstream services request the readmodel (via a query) the readmodel will be consistent.

I'll close this issue now.
