### ISSUE TITLE
Call for API changes for 1.0

### ISSUE THREAD

**Issue by rasmus** [rasmus/EventFlow#811]
If there are some API changes you would like to see for 1.0, please post them here.

**Comment by ProH4Ck** [comment]
#807 ? I could work on this tomorrow

**Comment by rasmus** [comment]
Perfect. If its possible to add without breaking changes, then it should be added to 0.x instead of 1.0 to make it available faster.

**Comment by ProH4Ck** [comment]
Ok, no problem

**Comment by ProH4Ck** [comment]
> Perfect. If its possible to add without breaking changes, then it should be added to 0.x instead of 1.0 to make it available faster.

Done in #817

**Comment by WardenUnleashed** [comment]
SerializedCommandPublisher should have its method's fixed such that they are correctly spelled!
