### ISSUE TITLE
Update readmodel outside of current context

### ISSUE THREAD

**Issue by alasdair-stark-screenmedia** [rasmus/EventFlow#828]
We have an event, `UpdateOrder`. The event is emitted by the `Order` aggregate. We have a read model, `ReadModel-OrderSummary` which subscribes to the event via the `IAmReadModelFor` interface.

When our API receives a request to change an order, we call the `ICommandBus.PublishAsync` method to publish an `UpdateOrder` command. The command handler invokes the aggregate method that emits the event. We await `PublishAsync` method so the request is not completed until all of the subscribers to the `UpdateOrder` event have completed. So the `ReadModel-OrderSummary` reflects the current state of the aggregate after the `PublishAsync` task has completed.

We are interesed in creating a new read model for reporting purposes, `ReadModel-OrderInsights`, which also subscribes to the `UpdateOrder` event and performs some more intensive processing. 

We do not require `ReadModel-OrderInsights` to be updated before completing the API request. However, from what I have read in the documentation, I cannot see way of processing the read model without blocking `PublishAsync`. The section of the documentation about Jobs was interesting but it doesn't seem related to read models.

**Comment by rasmus** [comment]
EventFlow does not return from the PublishAsync until all read models and subscribers are updated. However, depending on how you use EventFlow, it might be as simple as not awaiting or delighting to a background thread (if you want to handle potential errors).

**Comment by alasdair-stark-screenmedia** [comment]
In our case we want to wait for some read models to be updated but not wait for others. It sounds like there is currently no mechanism for this.
