### ISSUE TITLE
IJob

### ISSUE THREAD

**Issue by hughlee2016** [rasmus/EventFlow#830]
When I refer to the interface ijob, the first parameter of the method executeasync is iresolver resolver, not iserviceprovider serviceprovider. The code is as follows:

public interface IJob : IVersionedType

{

     Task ExecuteAsync(IResolver resolver, CancellationToken cancellationToken);

}

**Comment by rasmus** [comment]
This will be fixed as part of the version 1.0 release

https://github.com/eventflow/EventFlow/blob/develop-v1/Source/EventFlow/Jobs/IJob.cs
