### ISSUE TITLE
Question: Why store data in aggregate root?

### ISSUE THREAD

**Issue by Schwefelhexa** [rasmus/EventFlow#836]
In your [getting started doc page](https://docs.geteventflow.net/GettingStarted.html), you create an `ExampleAggregate` that stores a magic number, and updates it by applying an `ExampleEvent`.

But in order to actually read this number back in, we use the `ExampleReadModel` that has its own `Apply` function, basically implementing the same behavior as `ExampleAggregate.Apply()`.

This made me wonder why we even store any data in the aggregate root, if we can never access it?
I apologize if this has an obvious answer, I'm just getting started in Event Sourcing and still trying to wrap my head around it :D

**Comment by WardenUnleashed** [comment]
One of the benefits of event sourcing is the separation of your write model and your read model. Doing this does add complexity which makes the strategy may look over engineered when used in examples applications / simple domains.

Once you start requiring some more complex functionality though. You start to see more of the benefits.

[This article ](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs#when-to-use-this-pattern) may help you see some of the possible benefits you get from having your write store separated from your read store!

**Comment by Schwefelhexa** [comment]
Thank you for the answer! I think I realized what my mistake was.

In the example, `ExampleAggregate._magicNumber` is used for validation when `SetMagicNumer` is called.
Does this mean that I could use aggregate roots without any fields, as long as no command validation is needed?

**Comment by WardenUnleashed** [comment]
Yep! Maybe I'm not fully understanding your question but how you design / validate the aggregate is largely up to you.

**Comment by Schwefelhexa** [comment]
Okay, so the fields in aggregate roots are only meant for validation?

**Comment by WardenUnleashed** [comment]
> Okay, so the fields in aggregate roots are only meant for validation?

So I want to say no, I wouldn't say they are meant ONLY for validation. I think its better to think about your aggregates as a representation of your domain and the fields of your aggregate represent the current state of it.

If you wanted to you could just load that aggregate and use the state / field within the aggregates as way to query data relevant to that aggregate. Though you wouldn't want to do this due to performance reasons(thats why we have ReadModels).

**Comment by Schwefelhexa** [comment]
Okay, thank you for your help!
