### ISSUE TITLE
Cross assembly type cast exception when implementing a new AutofacAggregateFactory and using AutofacResolver.

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#87]
A cross assembly type cast issue forces the extension method to configure the aggregate factory to be implemented in eventflow.dll and not eventflow.autofac.dll.

__EXCEPTION DETAILS__
An exception of type 'System.InvalidCastException' occurred in EventFlow.Autofac.dll but was not handled in user code

Additional information: [A] EventFlow.Configuration.Registrations.AutofacResolver cannot be cast to[B] EventFlow.Configuration.Registrations.AutofacResolver.Type A originates from 'EventFlow, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\Jaco\Projects\EventFlowGuide\UsingAggregateState\bin\Debug\EventFlow.dll'. Type B originates from 'EventFlow.Autofac, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\Jaco\Projects\EventFlowGuide\UsingAggregateState\bin\Debug\EventFlow.Autofac.dll'.        
     
See https://github.com/JC008/EventFlow/tree/autofac-aggregatefactory for details

**Comment by rasmus** [comment]
@JC008 The reason for your problem, might be that you are casting to the `AutofacResolver` of the EventFlow.dll assembly, which is different from the one in the EventFlow.Autofac assembly.

To fix it, will need to use the `options.UseAutofacContainerBuilder(container)` and then `options.CreateContainer()` with will make sure that the Autofac types are the same types that you use in your assembly.

Its basically a ILmerge/assembly internal problem.

**Comment by JC008** [comment]
That worked - thanks.
