### ISSUE TITLE
EventFlowGuide

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#88]
I started a set of simple guides to using EventFlow. Every guide uses Nocco to generate line comments and guides to explain the code and use of EventFlow.

Your input would be appreciated.

See https://github.com/JC008/EventFlowGuide

**Comment by rasmus** [comment]
@JC008 I had a look, but some code seems to be missing. A clean checkout doesn't build.

**Comment by JC008** [comment]
Fixed it.
