### ISSUE TITLE
Add NOLOCK to MSSQL SELECT statements

### ISSUE THREAD

**Issue by rasmus** [rasmus/EventFlow#9]
As the title says

```sql
SELECT * FROM [dbo].[table1] WITH (NOLOCK)
```

**Comment by tabro** [comment]
@rasmus You sure you want this? Kasper Brandenburg had a talk a few days ago arguing against ever using NoLock - which is being deprecated from next MSSQL release.

**Comment by rasmus** [comment]
@tabro Doh!
