### ISSUE TITLE
Observation: Events by the same name in different namespaces targeting different aggregates won't work

### ISSUE THREAD

**Issue by fratting** [rasmus/EventFlow#903]
This may already be a known issue:
If you create an event class by the same name but in different namespaces and emit them from different aggregates eventflow doesn't exactly know when it rehydrates the event which aggregate the event should reapply to and can pick the wrong one. The easy work around is just to not reuse event names, though something to consider in future releases to maybe see about leveraging the associated aggregate name/type in the metadata.

**Comment by rasmus** [comment]
Its a known issue, to give your events custom names with e.g. a domain prefix, use the `[EventVersion]` attribute as documented here https://docs.geteventflow.net/GettingStarted.html#event

**Comment by rasmus** [comment]
Closing this as there's a work-round and an issue on improving it #907
