### ISSUE TITLE
Load aggregate at specific version

### ISSUE THREAD

**Issue by Athosone** [rasmus/EventFlow#906]
Hi !

In our company we are starting to use Eventflow.

We have a use case where we want to query the state of our aggregate between date range.

So far I did not see any out of the box way to do that. Did I miss something or did not understand a concept?

I think that I should use the event store and load all events for my aggregate then replay them until the desired date however I can foresee performance issue at some point.

This is where I may use snapshot, 

However I did not see a way to query a snapshot from a certain date...

Do you have any advice concerning this use case?

Regards

Ayrton

**Comment by rasmus** [comment]
Hi @Athosone

Just to make sure that I fully understand, you want to read the aggregate as it looked at a specific point in time? If so, then no, there isn't anything currently in the framework. But sounds like a useful thing to have.

I looked into the current available APIs and doing it yourself doesn't seem complicated. Read the events from the aggregate you are interested in via the `IEventStore`, do the required filtering, then create a new empty instance of your aggregate via the `IAggregateFactory` and simply invoke `ApplyEvents` with the list of filtered events on the aggregate.

**Comment by Athosone** [comment]
Thanks for the quick reply

Ok then I'll experiment with this, we could contribute eventually if that's something that may interest you?

**Comment by Athosone** [comment]
As for the snapshot I would need to implement a custom snapshot store which persist a new snapshot of the aggregate instead of updating the current one right ? using the timestamp / id as index

**Comment by Zev-OwitGlobal** [comment]
I have a similar need, so if it's something you want in EventFlow, I can fork and PR it for you. I would also be interested in helping contribute to the project, we are ramping up to use it here at my company. So let me know if you'd be interested in that as well.

**Comment by rasmus** [comment]
@Athosone did you see https://github.com/eventflow/EventFlow/issues/570

**Comment by rasmus** [comment]
Something like

```csharp
// Load events representing version
var domainEvents = IEventStore.LoadEventsAsync(id)
domainEvents = domainEvents.Where(e => e.AggregateSequenceNumber < selected version).ToList()

// Apply to empty aggregate
var aggregate = IAggregateFactory.CreateNewAggregateAsync(id)
aggregate.ApplyEvents(domainEvents)
```

**Comment by rasmus** [comment]
Will make it respect the stale exempt

**Comment by SeWaS** [comment]
@Athosone with the latest release ([v1.0.5007](https://github.com/eventflow/EventFlow/releases/tag/v1.0.5007)) `IEventStore` supports loading domain events within a given range of sequence numbers: https://github.com/eventflow/EventFlow/blob/develop-v1/Source/EventFlow/EventStores/IEventStore.cs#L54-L60

Maybe that helps already?

**Comment by rasmus** [comment]
Closing this as it as there wasn't a response after a posted solution/workaround. Reopen or open a new issue with reference to this if there's still something missing
