### ISSUE TITLE
EFCore 6 support (Missing method exception)

### ISSUE THREAD

**Issue by AlsenDev** [rasmus/EventFlow#909]
I get this exception when trying to call PublishAsync() from the CommandBus. It seems to be a problem that occurs when using EFCore 6. I got this exception while using EFCore 6.0.0-preview.7 with the newest version of EventFlow, but I get the same error on RC 2.

```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.
   at EventFlow.EntityFramework.ReadStores.EntityFrameworkReadModelStore`2.EntityDescriptor..ctor(DbContext context, IApplyQueryableConfiguration`1 queryableConfiguration)
   at EventFlow.EntityFramework.ReadStores.EntityFrameworkReadModelStore`2.<>c__DisplayClass16_0.<GetDescriptor>b__0(String s) in EventFlow.EntityFramework.dll:token 0x60000a7+0x0
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in System.Collections.Concurrent.dll:token 0x60000d3+0x10
   at EventFlow.EntityFramework.ReadStores.EntityFrameworkReadModelStore`2.GetDescriptor(DbContext context, IApplyQueryableConfiguration`1 queryableConfiguration) in EventFlow.EntityFramework.dll:token 0x600003d+0x35
   at EventFlow.EntityFramework.ReadStores.EntityFrameworkReadModelStore`2.GetAsync(TDbContext dbContext, String id, CancellationToken cancellationToken, Boolean tracking) in EventFlow.EntityFramework.dll:token 0x600003a+0x0
   at EventFlow.EntityFramework.ReadStores.EntityFrameworkReadModelStore`2.UpdateReadModelAsync(TDbContext dbContext, IReadModelContextFactory readModelContextFactory, Func`5 updateReadModel, CancellationToken cancellationToken, ReadModelUpdate readModelUpdate) in EventFlow.EntityFramework.dll:token 0x600003c+0xc6
   at EventFlow.Core.TransientFaultHandler`1.<>c__DisplayClass4_0.<<TryAsync>b__0>d.MoveNext() in EventFlow.dll:token 0x60009af+0x77
--- End of stack trace from previous location ---
```

I don't know if EFCore 6 support is planned yet, but I thought I at least should mention this error.

**Comment by rikp777** [comment]
A friend and I are going to take a look at it today to see if we can fix this

**Comment by rikp777** [comment]
Dear Rasmus 
For a graduate internship, I am working on updating an architecture for a company. Your repository fits this incredibly well, the only problem is that the current project needs to be developed in .net 6. Now I would really like to contribute to the project to help you upgrade EF to the current version, only I have some questions. 
First of all I would like to send you the link where I currently have the fork with the codebase: https://github.com/rikp777/EventFlow
As far as I think I understand it all, I have updated the class lib of entity framework to .net6.0. Now I do run into testing it all and how the assemblies should currently work. Based on the libs of mssql, mongodb and postgresql I have derived what I have now, but it remains difficult. Would you be able to support me with this? If so, please let me know.

**Comment by rthomson83** [comment]
I suspect this is due to framework targeting / version reference issues in the EventFlow.EntityFramework project; I found that EF Core 6 works if you register a new service with implementation of IEntityFrameworkReadModelStore<TReadModel> using the exact same code in the repo then it works fine. 
Only seems to be the read store side that's affected.

**Comment by jessemillerrev** [comment]
Is there an update on this? I cannot get it figured out and it is blocking me hard.

**Comment by jutimor** [comment]
You have to target EntityFrameworks nuget packages with version 5.X.X to have it working. Seems it won't be fixed in EventFlow 0.X but only in 1.X

**Comment by jessemillerrev** [comment]
I solved this by implementing my own EntityFrameworkReadModel service so it will use the EF version that my project uses instead of EventFlow as was suggested by @rthomson83 above. Even implemented its own extension method for UseEntityFrameworkReadModel. This is working perfectly and when/if this gets fixed in 1.X it should be simple to point back to the EventFlow version.

**Comment by nZeus** [comment]
@jessemillerrev do you have an example? I'm struggling with the same issue now..

**Comment by rthomson83** [comment]
> @jessemillerrev do you have an example? I'm struggling with the same issue now..

Start by adding a new store like this one:
https://github.com/rthomson83/eventflow-ef-core-fix/blob/main/EntityFrameworkCoreReadModelStore.cs

Then you can create a new extension method to make using it easier:
https://github.com/rthomson83/eventflow-ef-core-fix/blob/main/EFReadStoreExtensions.cs

Finally use/register the service via autofac however you are using that. For me it was a module that has all the EF configuration for eventflow read store side:
https://github.com/rthomson83/eventflow-ef-core-fix/blob/main/ReadStoreModule.cs

**Comment by jessemillerrev** [comment]
@rthomson83 I wish I had those links before I figured it all out! Thanks for posting that, hopefully others will benefit from your awesome work there.

**Comment by nZeus** [comment]
Thank you very much @rthomson83 for the snippets.
I've just checked and your implementation indeed solves the problem. Although I'm not sure if we can use this on production :(, unfortunately. I also noticed that it generates the wrong `Version` number (`0` instead of `1`)...

Thanks again!

**Comment by rthomson83** [comment]
> Thank you very much @rthomson83 for the snippets. I've just checked and your implementation indeed solves the problem. Although I'm not sure if we can use this on production :(, unfortunately. I also noticed that it generates the wrong `Version` number (`0` instead of `1`)...
> 
> Thank again!

No worries, I did notice that with the version but it does increment. I've not changed anything in the store (that's the original code from the event flow repo). I'm pretty sure the version is like that because its not been set default in the read model property Version, defined with the ConcurrencyCheck attribute. If you start it at 1 it would increment from there.
