### ISSUE TITLE
Configurable MongoDB Query BatchSize 

### ISSUE THREAD

**Issue by BerkCakir** [rasmus/EventFlow#957]
I'm using EventFlow with MongoDB eventstore. I really need a larger batch size while loading committed events. Is it possible to make this batch size configurable?

public async Task<IReadOnlyCollection<ICommittedDomainEvent>> LoadCommittedEventsAsync(IIdentity id, int fromEventSequenceNumber, CancellationToken cancellationToken)
        {
            return await MongoDbEventStoreCollection
              .Find(model => model.AggregateId == id.Value && model.AggregateSequenceNumber >= fromEventSequenceNumber,
                    **new FindOptions { BatchSize = desiredValue }**)
              .ToListAsync(cancellationToken)
              .ConfigureAwait(continueOnCapturedContext: false);
        }

Thanks.

**Comment by rasmus** [comment]
Seems easy enough
