### ISSUE TITLE
An error occurs when net6.0 uses UseFilesEventPersistence

### ISSUE THREAD

**Issue by LenFon** [rasmus/EventFlow#958]
An error occurs when net6.0 uses UseFilesEventPersistence (Invalid URI: The format of the URI could not be determined).

In the source code, this method only supports netcore3.0 and netcore3.1. Expect to be able to adjust to support versions above net3.1

![image](https://user-images.githubusercontent.com/7201759/194873563-433333ee-a23c-4d50-a84f-a12ca9099416.png)

**Comment by rasmus** [comment]
PR #961 fix this as the method is there. This was properly a leftover from .NET Framework that lacked the method
