### ISSUE TITLE
EntityFramework Dictionary Updates 

### ISSUE THREAD

**Issue by FinalFortune** [rasmus/EventFlow#959]
I'm using [JsonExtensionData](https://www.newtonsoft.com/json/help/html/t_newtonsoft_json_jsonextensiondataattribute.htm) for an entity and its ReadModel.    Updates don't seem to be always propagated to the database.

```
    modelBuilder.Entity<MyReadModel>()
        .Property(b => b.AdditionalProperties)
        .HasConversion(
            v => JsonConvert.SerializeObject(v),
            v => JsonConvert.DeserializeObject<Dictionary<string, object>>(v));
```

I read that `Update` must be explicitly called on the dbset/entity for the above modification to allow for change tracking to work.

I'm not entirely sure what the best solution to this would be, perhaps this isn't an issue with [property bags](https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties#property-bag-entity-types), but I think that is a feature provided by later entityframework versions after the version used in this project.

Perhaps best to have this entity update its custom values purely by serializing a JSON string and have the field as JSON. However, I do have use cases where the additional property structure will be navigated and used.

Perhaps I need to add an update somewhere here
https://github.com/eventflow/EventFlow/blob/369042002f7a7c00fe27b3e21094c95624866187/Source/EventFlow.EntityFramework/ReadStores/EntityFrameworkReadModelStore.cs#L244?

**Comment by rasmus** [comment]
Can you reproduce the problem in a PR for one of the EF integration tests?
