### ISSUE TITLE
A way to configure JsonSerializerSettings at JsonSerializer

### ISSUE THREAD

**Issue by nazarovsa** [rasmus/EventFlow#966]
Hi, I'm enjoying EventFlow, but I faced a problem with event deserialization.
I have field of interface type in my AggregateEvent. I wrote a JsonConverter for it, but I can't find a way to configure json settings inside `JsonSerializer` class. 
I tried next, but there is no effect: `JsonSerializerSettings` inside `JsonSerializer` still the same.
```csharp
builder.Services.AddEventFlow(options =>
{
    options.ConfigureJson(jsonOptions =>
        {
            jsonOptions.Apply(JsonSettings.Instance);
            jsonOptions.AddConverter<CharacterJsonConverter>();
            return jsonOptions;
        })
        // Next registrations
});
```
Additionally, I noticed that [`JsonOptions.Apply`](https://github.com/eventflow/EventFlow/blob/develop-v1/Source/EventFlow/Configuration/Serialization/JsonOptions.cs#L30) do nothing. Is it expected behaviour?

```csharp
public class JsonOptions : IJsonOptions
    {
        public void Apply(JsonSerializerSettings settings)
        {
        }

        public static JsonOptions New => new JsonOptions();
    }
```
Is there way to configure `JsonSerializerSettings` at `JsonSerializer` class?

**Comment by rasmus** [comment]
The default `IJsonOptions` implementation does nothing. You would simply register an alternative implementation that does something else.

It's properly something that could be cleaned up a bit for 1.x
