### ISSUE TITLE
Event rollback during Saga failure?

### ISSUE THREAD

**Issue by gutsdream** [rasmus/EventFlow#971]
I've looked through the documentation and source material but couldn't find any information regarding this; sorry if I've missed something obvious. 

I'm wondering if there's a way to rollback events and read model updates upon Saga failure (or to only commit them upon completion). 

If this isn't supported functionality - what's the best way to support something where there's one transaction that spans multiple aggregates and domain events? Using a single Command/ CommandHandler?

Also I just wanted to say thanks for creating this framework, it's awesome!

**Comment by gutsdream** [comment]
I've done some more research into this in the meantime and have come across this article, which has shed some light for me: https://www.zilverline.com/blog/event-sourcing-invariants-spanning-multiple-aggregates 

Would this be the right direction to go in rather than trying to force an atomic style into the framework?

**Comment by jutimor** [comment]
Good article and i agree with it. Events are immutable and should never disappear(except in clean of old data) .
The only "good" way to cancel something is a CancelEvent that keep track that somethings change and why.
